### ISSUE TITLE
AuthorizeUrl does not handle url parse errors

### ISSUE THREAD

**Issue by gcfresh** [bold-commerce/go-shopify#126]
`AuthorizeUrl` does not handle errors.  If `url.Parse` returns an error then a panic occurs trying to access a nil pointer.  This can occur if the `shopName` contains invalid web address characters like a space.

[AuthorizeURL in oauth.go](https://github.com/bold-commerce/go-shopify/blob/master/oauth.go#L25)
```
func (app App) AuthorizeUrl(shopName string, state string) string {
	shopUrl, _ := url.Parse(ShopBaseUrl(shopName)) // error here is unhandled
	shopUrl.Path = "/admin/oauth/authorize" // panic occurs here on nil pointer
	query := shopUrl.Query()
	query.Set("client_id", app.ApiKey)
	query.Set("redirect_uri", app.RedirectUrl)
	query.Set("scope", app.Scope)
	query.Set("state", state)
	shopUrl.RawQuery = query.Encode()
	return shopUrl.String()
}
```

**Comment by BoldBrandonM** [comment]
Checking in here to echo the concerns you bring up. Calls to the library should not cause runtime panic scenarios, and instead should bubble up the error for consumer handling as per GoLang standard practice. 

This issue has caused us to need a workaround in our production code, and should be resolved as a part of the next major version upgrade due to the breaking nature of the required change.

**Comment by oliver006** [comment]
Tackling this in #258

**Comment by oliver006** [comment]
[v4.0.0](https://github.com/bold-commerce/go-shopify/releases/tag/v4.0.0) was released - this should be fixed.
